### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by ULTIMATEUPGRADE** [mrhanlon/less-than-slash#26]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Linux Mint
**Thrown From**: [less-than-slash](https://github.com/mrhanlon/less-than-slash) package, v0.12.1

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /home/harmony-12/.atom/packages/less-than-slash/lib/less-than-slash.coffee:46

TypeError: Cannot read property 'dispose' of undefined
    at /home/harmony-12/.atom/packages/less-than-slash/lib/less-than-slash.coffee:46:31
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.destroy (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1191:29)
    at TextBuffer.module.exports.TextBuffer.release (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1215:14)
    at TextEditor.module.exports.TextEditor.destroyed (/usr/share/atom/resources/app.asar/src/text-editor.js:241:19)
    at TextEditor.module.exports.Model.destroy (/usr/share/atom/resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:455:18)
    at atom-tabs.TabBarView.onClick (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
     -5:03.1.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:03.1.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:02.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:02.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:02.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:02.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:02.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:02.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -5:01.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -5:01.8.0 core:cancel (atom-text-editor.editor.is-focused)
  2x -4:59.4.0 core:copy (atom-text-editor.editor.is-focused)
     -4:57.6.0 project-find:show (atom-text-editor.editor.is-focused)
     -4:57.1.0 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -4:56 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:15.9.0 core:cancel (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:06.6.0 pane:split-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-tidy",
      "linter-shellcheck",
      "linter-pylint",
      "git-control"
    ],
    "ignoredNames": [
      "*.pyc",
      "*.project",
      "*.pydevproject",
      "*.settings"
    ],
    "projectHome": "/home/harmony-12/Desktop/karthik/Text-File"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.21
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-plus, v2.25.0
bottom-dock, v0.3.7
color-picker, v2.1.0
compare-files, v0.6.2
file-icons, v1.6.14
highlight-selected, v0.11.1
language-diff, v0.4.0
language-xml, v0.34.2
less-than-slash, v0.12.1
linter, v1.11.3
linter-csslint, v1.2.0
linter-js-yaml, v1.2.5
linter-jshint, v1.2.2
linter-jsonlint, v1.1.4
linter-manager, v0.2.8
linter-pep8, v1.2.1
minimap, v4.19.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
odoo-snippets, v0.2.0
spell-check, v0.65.0
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by paper9oll** [comment]
same issue here

**Comment by mrhanlon** [comment]
Thanks for the report. I'll try to get this fixed this weekend.

**Comment by mostafa-raafat** [comment]
any solution ??

**Comment by mrhanlon** [comment]
Hey sorry folks. I was finally able to reproduce this when splitting and then closing that split pane. However, this has revealed a new issue that the listener attaches to the buffer twice when you split the pane. I will open an issue for fixing that.
